### ISSUE TITLE
`aws-lambda` package is not necessary

### ISSUE THREAD

**Issue by moltar** [berenddeboer/cdk-rds-sql#10]
https://github.com/berenddeboer/cdk-rds-sql/blob/2ee7dd1e969bb7b0d7291faa0d6b66f49c34498b/.projenrc.ts#L39

It is not part of the `@types/aws-lambda` combo. It's an entirely different package, that does something else.

https://www.npmjs.com/package/aws-lambda

**Comment by berenddeboer** [comment]
hah lol, wasn't using it at all either, not sure how that snuck in.
