### ISSUE TITLE
lambda in isolated network will fail to get secret

### ISSUE THREAD

**Issue by gdamjan** [berenddeboer/cdk-rds-sql#14]
> feat: place sql lambda handler explicitly in a private isolated network 

this will break getting the RDS Secret unless you have also enabled the VPC endpoint for secrets manager.
at minimum, this dependency will need to be documented.

**Comment by ww-daniel-mora** [comment]
@gdamjan I may be running into this issue. Could you please add an example for how you resolved this?

**Comment by gdamjan** [comment]
> @gdamjan I may be running into this issue. Could you please add an example for how you resolved this?

you can explicitly specify the subnet where the lambda will run or add a secretsmanager vpc endpoint

**Comment by ww-daniel-mora** [comment]
@gdamjan I've explicitly placed the lambda in the same subnet as the database which, like the example, is maked `PRIVATE_ISOLATED` and I suspect that is blocking the retrieval of secrets. An example of how to 

> add a secretsmanager vcp endpoint

would be very helpful. I've been spending a few days reading up on VPC terminology to in an attempt to do just that.

**Comment by berenddeboer** [comment]
@ww-daniel-mora have added an example to the docs. Let me know if this worked!
