### ISSUE TITLE
Database does not exist error when using alternate root username

### ISSUE THREAD

**Issue by RedbackThomson** [berenddeboer/cdk-rds-sql#4]
When creating an `rds.DatabaseCluster` and a `Role` with the option `credentials: rds.Credentials.fromGeneratedSecret("my-username"),`, the Lambda function returns the following error:
```
Received response status [FAILED] from custom resource. Message returned: database "my-username" does not exist
```

I believe this is happening because the [database config](https://github.com/berenddeboer/cdk-rds-sql/blob/main/src/handler.ts#L260) when establishing a client uses [`event.ResourceProperties.Database`](https://github.com/berenddeboer/cdk-rds-sql/blob/main/src/handler.ts#L214). However, the `Role` custom resource doesn't define a `Database` property in [its outputs to the handler](https://github.com/berenddeboer/cdk-rds-sql/blob/main/src/role.custom-resource.ts#L53-L59). The [default fallback for the `pg.Client` object](https://node-postgres.com/apis/client#new-client) is to use the username. For Aurora Postgres, the default database name is `postgres` and not the username.

To fix this, the custom resource should try to use the following for the value of `ResourceProperties.Database`:
- Check to see if `cluster.defaultDatabaseName` is set and use that value
- Use the default engine value of `postgres` for Postgres

The current implementation only works if `credentials` is not set on the `rds.DatabaseCluster` and it defaults to `postgres`, or if the generated username happens to also be `postgres`

**Comment by berenddeboer** [comment]
This was fixed in a recent release.
