### ISSUE TITLE
Password for the new role is logged

### ISSUE THREAD

**Issue by moltar** [berenddeboer/cdk-rds-sql#5]
The following line will log the password into the CloudWatch log for the Lambda handler:

https://github.com/berenddeboer/cdk-rds-sql/blob/2ee7dd1e969bb7b0d7291faa0d6b66f49c34498b/src/handler.ts#L254

![screenshot-20230320T224908-s4jDaGWN@2x](https://user-images.githubusercontent.com/491247/226482655-a8febab8-11e9-498e-91c6-b3d1429acff4.png)

**Comment by berenddeboer** [comment]
Yeah, oversight, logging is turned off, unless you enable it now.
