### ISSUE TITLE
Timeout is very low

### ISSUE THREAD

**Issue by moltar** [berenddeboer/cdk-rds-sql#7]
This timeout value is low, especially for RDS Serverless v1, which _can_ be sleeping and needs time to wake up.

https://github.com/berenddeboer/cdk-rds-sql/blob/2ee7dd1e969bb7b0d7291faa0d6b66f49c34498b/src/handler.ts#L261

I don't see any harm in setting this higher, as CloudFormation is slow.

**Comment by berenddeboer** [comment]
Ah that way, agree, but does it wake up in 30 seconds and connect? Anyway, v1 is no longer supported end of the year.
